import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased" style={{ fontFamily: 'system-ui, sans-serif' }}>
        {children}
        {/* Footer */}
        <footer className="w-full bg-gradient-to-t from-blue-50 to-white border-t border-blue-100 mt-10 pt-10 pb-6 px-4 sm:px-10">
          <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between gap-8 md:gap-0">
            {/* Logo & Social */}
            <div className="flex-1 flex flex-col items-center md:items-start mb-6 md:mb-0">
              <div className="flex items-center gap-2 mb-3">
                <img src="/qemerlogo.png" alt="Qemer Logo" className="w-14 h-14 rounded-full" />
                <span className="text-2xl font-bold text-blue-900 tracking-wide">QEMER</span>
              </div>
              <span className="text-gray-600 mb-2">follow us on:</span>
              <div className="flex gap-3">
                <a href="#" aria-label="Facebook" className="text-gray-500 hover:text-blue-600 text-2xl" target="_blank" rel="noopener noreferrer">
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M22.675 0h-21.35C.595 0 0 .592 0 1.326v21.348C0 23.408.595 24 1.325 24h11.495v-9.294H9.692v-3.622h3.128V8.413c0-3.1 1.893-4.788 4.659-4.788 1.325 0 2.463.099 2.797.143v3.24l-1.918.001c-1.504 0-1.797.715-1.797 1.763v2.313h3.587l-.467 3.622h-3.12V24h6.116C23.406 24 24 23.408 24 22.674V1.326C24 .592 23.406 0 22.675 0"/></svg>
                </a>
                <a href="#" aria-label="LinkedIn" className="text-gray-500 hover:text-blue-700 text-2xl" target="_blank" rel="noopener noreferrer">
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-10h3v10zm-1.5-11.268c-.966 0-1.75-.784-1.75-1.75s.784-1.75 1.75-1.75 1.75.784 1.75 1.75-.784 1.75-1.75 1.75zm13.5 11.268h-3v-5.604c0-1.337-.025-3.063-1.868-3.063-1.868 0-2.154 1.459-2.154 2.968v5.699h-3v-10h2.881v1.367h.041c.401-.761 1.381-1.563 2.841-1.563 3.039 0 3.6 2.001 3.6 4.601v5.595z"/></svg>
                </a>
                <a href="#" aria-label="YouTube" className="text-gray-500 hover:text-red-600 text-2xl" target="_blank" rel="noopener noreferrer">
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M23.498 6.186a2.994 2.994 0 0 0-2.112-2.112C19.458 3.5 12 3.5 12 3.5s-7.458 0-9.386.574a2.994 2.994 0 0 0-2.112 2.112C0 8.114 0 12 0 12s0 3.886.502 5.814a2.994 2.994 0 0 0 2.112 2.112C4.542 20.5 12 20.5 12 20.5s7.458 0 9.386-.574a2.994 2.994 0 0 0 2.112-2.112C24 15.886 24 12 24 12s0-3.886-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z"/></svg>
                </a>
                <a href="#" aria-label="Instagram" className="text-gray-500 hover:text-pink-500 text-2xl" target="_blank" rel="noopener noreferrer">
                  <svg width="24" height="24" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2.163c3.204 0 3.584.012 4.85.07 1.366.062 2.633.334 3.608 1.308.974.974 1.246 2.242 1.308 3.608.058 1.266.069 1.646.069 4.851s-.011 3.584-.069 4.85c-.062 1.366-.334 2.633-1.308 3.608-.974.974-2.242 1.246-3.608 1.308-1.266.058-1.646.069-4.85.069s-3.584-.011-4.85-.069c-1.366-.062-2.633-.334-3.608-1.308-.974-.974-1.246-2.242-1.308-3.608C2.175 15.647 2.163 15.267 2.163 12s.012-3.584.07-4.85c.062-1.366.334-2.633 1.308-3.608.974-.974 2.242-1.246 3.608-1.308C8.416 2.175 8.796 2.163 12 2.163zm0-2.163C8.741 0 8.332.013 7.052.072 5.771.131 4.659.425 3.678 1.406c-.981.981-1.275 2.093-1.334 3.374C2.013 5.668 2 6.077 2 12c0 5.923.013 6.332.072 7.612.059 1.281.353 2.393 1.334 3.374.981.981 2.093 1.275 3.374 1.334C8.332 23.987 8.741 24 12 24s3.668-.013 4.948-.072c1.281-.059 2.393-.353 3.374-1.334.981-.981 1.275-2.093 1.334-3.374.059-1.28.072-1.689.072-7.612 0-5.923-.013-6.332-.072-7.612-.059-1.281-.353-2.393-1.334-3.374-.981-.981-2.093-1.275-3.374-1.334C15.668.013 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zm0 10.162a3.999 3.999 0 1 1 0-7.998 3.999 3.999 0 0 1 0 7.998zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z"/></svg>
                </a>
              </div>
            </div>
            {/* Quick Links */}
            <div className="flex-1 mb-6 md:mb-0 flex flex-col items-center md:items-start">
              <h3 className="text-lg font-bold text-blue-800 mb-3">Quick Links</h3>
              <ul className="space-y-2">
                <li><a href="/" className="text-gray-700 hover:text-cyan-600 transition">Home</a></li>
                <li><a href="/courses" className="text-gray-700 hover:text-cyan-600 transition">Browse Courses</a></li>
                <li><a href="/register/1" className="text-gray-700 hover:text-cyan-600 transition">Register</a></li>
                <li><a href="/contact" className="text-gray-700 hover:text-cyan-600 transition">Contact</a></li>
                <li><a href="#about" className="text-gray-700 hover:text-cyan-600 transition">About Us</a></li>
              </ul>
            </div>
            {/* Contact Info */}
            <div className="flex-1 flex flex-col items-center md:items-start">
              <h3 className="text-lg font-bold text-blue-800 mb-3">Contact Info</h3>
              <ul className="space-y-3 text-gray-700">
                <li className="flex items-center gap-2"><span className="text-xl">📍</span> Meskel Flower, Addis Ababa, Ethiopia</li>
                <li className="flex items-center gap-2"><span className="text-xl">📞</span> +251-912-970-734</li>
                <li className="flex items-center gap-2"><span className="text-xl">✉️</span> <a href="mailto:contactus@qemertech.com" className="hover:text-cyan-600">contactus@qemertech.com</a></li>
              </ul>
            </div>
          </div>
          <div className="mt-8 text-center text-gray-500 text-sm">
            © 2024 Qemer Software Technology PLC. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
